"""Initial migration

Revision ID: dbe90f917146
Revises:
Create Date: 2026-03-22 11:06:26.794798
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbe90f917146"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gps_track_points",
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.Column("accuracy", sa.Float(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.Column("bearing", sa.Float(), nullable=True),
        sa.Column("is_filtered", sa.Boolean(), nullable=False),
        sa.Column("filter_latitude", sa.Float(), nullable=True),
        sa.Column("filter_longitude", sa.Float(), nullable=True),
        sa.Column("filter_altitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("time", "session_id"),
    )
    op.create_index(
        "idx_gps_session_time", "gps_track_points", ["session_id", "time"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_gps_session_time", table_name="gps_track_points")
    op.drop_table("gps_track_points")
    # ### end Alembic commands ###
